using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace IOT_DEVICE_CRUD.manifests
{
    class deployment
    {
    apiVersion : apps/v1
	kind: Deployment
	metadata:
	  name: iotdeviceapi 
	spec:
	  replicas: 1
	  selector:
	    matchLabels:
	      app: iotdeviceapi
	  template:
	    metadata:
	      labels:
	        app: iotdeviceapi 
	    spec:
	      containers:
	        - name: iotdeviceapi 
	          image: iotdeviceapiacr.azurecr.io/iotdeviceapi
	          ports:
	          - containerPort: 80


    }
}
